### PR TITLE
K:D Ratio Improvement #10

### PR DESCRIPTION
**Pull request by BrendonButler**
Resolved large K:D ratio issue.

### CODE REVIEW

**Comment by hhaslam11** [comment]
Awesome, Thanks!

**Comment by hhaslam11** [comment]
Just wondering: What does 'gcm' stand for in the context you're using it in?

**Comment by BrendonButler** [comment]
Greatest Common Multiple. I have another method that finds the Least Common
Multiple (LCM). Will be committing soon hopefully for my first full release.

**Comment by hhaslam11** [comment]
Ah, thanks. Seems to work good unless either 'first' or 'second' is 0, then it gets a bit confused, but not a big deal right now :) Thanks again!

**Pull request merged**
